exec-once = waybar
exec-once = hyprpaper
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = dunst
exec-once = ydotoold

exec-once = ~/.config/hypr/xdg-portal-hyprland
exec-once = ~/.config/hypr/script/random_wallpaper.sh