decoration {
    rounding = 10

    dim_inactive = true
    dim_strength = 0.2

    blur {
        enabled = true
        size = 7
        passes = 3
    }

    shadow {
        enabled = true
        range = 10
    }
}