general {
    #gaps
    gaps_in = 5
    gaps_out = 10
    gaps_workspaces = 50

    #border
    border_size = 2
    col.active_border = rgb(7AA2F7)
    col.inactive_border = rgba(595959aa)
    resize_on_border = true
    hover_icon_on_border = true

    #layout
    layout = dwindle

    snap {
        enabled = true
    }
}

#dwindle settings
dwindle {
    pseudotile = true
    preserve_split = true
}

#misc
misc {
    allow_session_lock_restore = true
}

#XWayland
xwayland {
    force_zero_scaling = true
}