input {
    kb_layout = de
    kb_variant =
    kb_model = pc105
    kb_options =
    kb_rules =

    repeat_delay = 300

    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}