input {
    kb_layout = de,de
    kb_variant = mac,nodeadkeys
    follow_mouse = 1

    #sensitivity = -0.4
}

#cursor settings
env = XCURSOR_SIZE,24 #fix cursor being bigger on XWayland applications
