monitorv2 {
    output = DP-3
    mode = 3840x2160@160
    position = 0x0
    scale = 1.5
    bitdepth = 10
    supports_wide_color = 1
    supports_hdr = 1
    max_luminance = 1000
    min_luminance = 0
    sdr_max_luminance = 400
    sdr_min_luminance = 0
    cm = hdr
}

monitor = DP-2, 3840x2160@60, 2560x0, 1.5, transform, 3

render {
    cm_fs_passthrough = 1
}