layerrule = noanim, selection
layerrule = blur, waybar
layerrule = blur, ghostty
layerrule = blur, rofi
layerrule = ignorealpha, rofi
layerrule = blur, notifications
layerrule = blur, rust-muted-overlay
layerrule = blur, rdock
